### ISSUE TITLE
Password reset policy implementation on angular 

### ISSUE THREAD

**Issue by patolax** [Azure-Samples/active-directory-b2c-javascript-angular-spa#15]
I was not able to initiate password reset flow on my angular client. 
The user clicks on a button that executes the following code. changePasswordUrl is the url from the Azure B2C portal with B2C_1_reset policy.

  changePassword() {
    localStorage.clear();
    window.location.href = this.changePasswordUrl;
  }

Upon redirection user is redirected to the proper page, however, if the user cancels the reset password page, the redirection ends up with 

` Unexpected error in authentication.: Hash does not contain state.
    at new AuthError (http://localhost:7100/vendor.js:211125:28)
    at Function.push../node_modules/msal/lib-es6/error/AuthError.js.AuthError.createUnexpectedError (http://localhost:7100/vendor.js:211133:16)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.getResponseState (http://localhost:7100/vendor.js:209268:79)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (http://localhost:7100/vendor.js:209206:30)`

How to properly and securely initiate password reset flow?

**Comment by derisen** [comment]
@patolax if I understand you correctly, there is no issue with resetting the password itself -your issue is that if the user cancels the flow prematurely, the error above occurs. Is that the case?

**Comment by patolax** [comment]
I used your sample and implemented  _reset password flow_. 
**Question 1**
To change the password we have to use _reset password flow_ right. Authenticated users cant just change the password without email verification like in normal change password feature.

**Question 2**
I had to comment out section below in order to get things working. My token does not have the _acr_ attribute. Is commenting out this section ok, or how do I get _acr_ attribute into my token.
if (success.idToken.claims['acr'] !== b2cPolicies.names.signUpSignIn) {
  window.alert("Password has been reset successfully. \nPlease sign-in with your new password");
 return this.authService.logout()
}

Thanks.

**Comment by digitalcraftco** [comment]
> I had to comment out section below in order to get things working. My token does not have the _acr_ attribute. Is commenting out this section ok, or how do I get _acr_ attribute into my token.

@patolax Did you try **tfp** instead of **acr**? These settings can be found in B2C > User FLow > Token compatibility settings.

![image](https://user-images.githubusercontent.com/4356929/90657097-c9fe0780-e1ff-11ea-8fda-606ddd7f48ac.png)

**Comment by derisen** [comment]
@patolax to get to your questions:

**1)** That's correct, email verification is necessary for changing the password.

**2)** In the `app.component.ts`, it is mentioned that newer policies should use `tfp` instead of `acr`:

```typescript
    // We need to reject id tokens that were not issued with the default sign-in policy.
    // "acr" claim in the token tells us what policy is used (NOTE: for new policies (v2.0), use "tfp" instead of "acr")
    // To learn more about b2c tokens, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview
      if (success.idToken.claims['acr'] !== b2cPolicies.names.signUpSignIn) {
        window.alert("Password has been reset successfully. \nPlease sign-in with your new password");
        return this.authService.logout()
      }
```

**Comment by patolax** [comment]
thanks for your response. 

I am already using tfp, so I will comment out the section. My app is a new release so we don't have other configurations.
