### ISSUE TITLE
Silent renewal or sign-in flow is initiated every backend or navigation call

### ISSUE THREAD

**Issue by patolax** [Azure-Samples/active-directory-b2c-javascript-angular-spa#17]
I migrated to MsalModule setup shown in this sample from **forRoot** configuration that was previously available. 

However, after successful login, every time I make an api call using httpclient, the first two items on the network tab are as follows. These two initiate some sort of silent sign-in flow every time which creates so many delays and errors. 

https://fakeb2c.b2clogin.com/fakeb2c.onmicrosoft.com/b2c_1_signin/v2.0/.well-known/openid-configuration
https://fakeb2c.b2clogin.com/fakeb2c.onmicrosoft.com/b2c_1_signin/oauth2

However, if I use the same configuration parameters and stick to my previous configuration shown below, everything runs smoothly. _Any particular reason for this behavior?_ I would like to use the new setup in this sample so that I can load the configuration file dynamically. 

MsalModule.forRoot(msalConfig,
      {
        popUp: false,
        consentScopes: ['openid', ...apiConfig.b2cScopes],
        unprotectedResources: [],
        protectedResourceMap: [
          [apiConfig.webApi, apiConfig.b2cScopes],
        ],
        extraQueryParameters: {},
      })

**Comment by derisen** [comment]
@jasonnutter any ideas? the sample loads the configuration from [this](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa/blob/master/src/app/app-config.ts).

**Comment by jasonnutter** [comment]
@patolax Can you share any logs from the MSAL logger?

**Comment by patolax** [comment]
this is what I get when I make a simple http backend call

[DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:36 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:36 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info LoadFrame: msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:36 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
:7100/#state=7d4450c7-afed-4e6a-962e-32bac540bec6&client_info=[TOKEN]&token_type=Bearer&expires_in=3600&scope=https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2fvoice_read+https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2ftenant_voice_read+https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2ftenant_voice_write:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:7100/Roboto-Regular.woff2
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Returned from redirect url
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Processing the callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State status:true; Request type:RENEW_TOKEN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Fragment has access token
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info The user object received in the response is the same as the one passed in the acquireToken request
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info LoadFrame: msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:37 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
:7100/#state=8b98d967-2d49-41eb-9abb-5462610c6faf&client_info=[TOKEN]A&token_type=Bearer&expires_in=3600&scope=https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2fvoice_read+https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2ftenant_voice_read+https%3a%2f%2ffakeb2cdev1.onmicrosoft.com%2ffakeb2capi%2ftenant_voice_write:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:7100/Roboto-Regular.woff2
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Returned from redirect url
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Processing the callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State status:true; Request type:RENEW_TOKEN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Fragment has access token
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:38 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info The user object received in the response is the same as the one passed in the acquireToken request
WindowUtils.js:160 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:7100/Roboto-Regular.woff
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:39 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:39 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info LoadFrame: msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:39 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Returned from redirect url
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Processing the callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State status:true; Request type:RENEW_TOKEN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Fragment has access token
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info The user object received in the response is the same as the one passed in the acquireToken request
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info LoadFrame: msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:40 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Add msal frame to document:msalRenewFramehttps://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/voice_write https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_read https://fakeb2cdev1.onmicrosoft.com/fakeb2capi/tenant_voice_write
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Returned from redirect url
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Processing the callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State status:true; Request type:RENEW_TOKEN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info Fragment has access token
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Wed, 26 Aug 2020 01:10:41 GMT:476e85a7-05d6-4254-856c-3cb395a8319b-1.2.2-Info The user object received in the response is the same as the one passed in the acquireToken request

**Comment by patolax** [comment]
Any luck with this issue?

**Comment by derisen** [comment]
sorry for delay @patolox -I couldn't replicate the same behavior. Would you mind updating your msal and msal-angular to the latest? @jasonnutter can you help us here?

**Comment by Patolox** [comment]
> sorry for the delay @Patolox -I couldn't replicate the same behavior. Would you mind updating your msal and msal-angular to the latest? @jasonnutter can you help us here?

what? i think you @ the wrong person, lol.

**Comment by derisen** [comment]
> > sorry for the delay @Patolox -I couldn't replicate the same behavior. Would you mind updating your msal and msal-angular to the latest? @jasonnutter can you help us here?
> 
> what? i think you @ the wrong person, lol.

apparently : )) -sorry about that

**Comment by derisen** [comment]
@patolax I would recommend opening an issue at the [main MSAL.js repository](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) for better help. Feel free to close this one after.

**Comment by patolax** [comment]
Thanks for the help, I worked on this last few days in order to report back the results.

I am using angular 7. Not planning to upgrade to 9 anytime soon which is used by the sample.
upgraded
"@azure/msal-angular": "^1.0.0-beta.4"	to "@azure/msal-angular": "^1.0.0",
"msal": "^1.2.2-beta.2" 		                        to "msal": "^1.3.4",


The issue at the moment is when we load modules dynamically as shown below., token renewal (_authorize?response_type=id_toke_), and redirect happens.  I have shown the log below. Is this the desired behavior? Or is there someting going on with **MsalGuard**.

**app-routing.module**
  {
    path: 'alarm',
    loadChildren: './features/alarms/mycar.module#CarModule',
    canActivate: [MsalGuard]
  },

[DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:53:48 GMT:4b5f7038-7ef2-4484-9397-4884b17f448e-1.4.0-Info RenewIdToken has been called
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:53:49 GMT:4b5f7038-7ef2-4484-9397-4884b17f448e-1.4.0-Info ProcessCallBack has been called. Processing callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:53:49 GMT:4b5f7038-7ef2-4484-9397-4884b17f448e-1.4.0-Info State status: true; Request type: LOGIN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:53:49 GMT:4b5f7038-7ef2-4484-9397-4884b17f448e-1.4.0-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:53:49 GMT:4b5f7038-7ef2-4484-9397-4884b17f448e-1.4.0-Info Fragment has idToken

**Comment by patolax** [comment]
ok, I was able to recreate the problem I am facing using this sample.

Rough source code can be found here. It's not working due to import issues.
https://stackblitz.com/edit/angular-ivy-9q36dx?file=src/app/app.component.ts

Please copy across the profile module and changes I have done to the home component and app routing module. Then run the application locally.

**Reproduce steps.**

First login which will redirect to home. Then press _Call Api_ to navigate to the profile module.
The network tab of dev console will show
profile-profile-module.js	
authorize?response_type=token....
vendor.js
main.js
......


Console tab will show
access token acquired at: Fri Sep 04 2020 11:50:06 GMT+1000 (Australian Eastern Standard Time)
profile.component.ts:27 {uniqueId: "", tenantId: "", tokenType: "id_token", idToken: IdToken, idTokenClaims: {…}, …}
app.component.ts:67 MSAL Logging:  Fri, 04 Sep 2020 01:50:07 GMT:f8d1da58-2c74-45e7-a715-aa0178d16d76-1.3.4-Info ProcessCallBack has been called. Processing callback from redirect response
app.component.ts:67 MSAL Logging:  Fri, 04 Sep 2020 01:50:07 GMT:f8d1da58-2c74-45e7-a715-aa0178d16d76-1.3.4-Info State status: true; Request type: RENEW_TOKEN
app.component.ts:67 MSAL Logging:  Fri, 04 Sep 2020 01:50:07 GMT:f8d1da58-2c74-45e7-a715-aa0178d16d76-1.3.4-Info State is right
app.component.ts:67 MSAL Logging:  Fri, 04 Sep 2020 01:50:07 GMT:f8d1da58-2c74-45e7-a715-aa0178d16d76-1.3.4-Info Fragment has access token
app.component.ts:67 MSAL Logging:  Fri, 04 Sep 2020 01:50:07 GMT:f8d1da58-2c74-45e7-a715-aa0178d16d76-1.3.4-Info The user object received in the response is the same as the one passed in the acquireToken request
profile.component.ts:26 access token acquired at: Fri Sep 04 2020 11:50:07 GMT+1000 (Australian Eastern Standard Time)

In my case, I see the same behavior when I navigate to a new module from the side nav every time. This is a redirect and app refresh every time we go to a new module. 

Please have a look and let us know if this is a issue, if so how to fix it.

**Comment by jmprieur** [comment]
@patolax you can avoid this by pre-authorizing all the web apis that you want to call (Admin consent) in the app registration portal. This way the user won't be exposed to incremental consent.

**Comment by patolax** [comment]
![image](https://user-images.githubusercontent.com/29444156/92341026-cb846680-f0ff-11ea-99a3-62106d8eded0.png)

I think I have done that already.

**Comment by derisen** [comment]
@patolax I was unable to run your project. The page seem to stuck at "loading" stage. You also seem to have a `profile-guard` module that might be causing and/or related to this. Would you mind ensuring that the project runs on another machine? Also, I'll again advise you to take this issue to the [main msal.js repository](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues) to get better help.

**Comment by patolax** [comment]
Ok, I have published it on
https://github.com/patolax/active-directory-b2c-javascript-angular-spa-master

Change the config to your b2c configuration.
Then login which will redirect to home. Then press Call Api to navigate to the profile module.
This will show you the token renewal again.

It could be a config issue on my tenant or sample issue. I need that to be clear before reporting to msal project.

Please see if you can recreate it. 
Thanks.

**Comment by derisen** [comment]
@patolax I haven't been able to run your project again. I had to set `enableIvy` to `false` in `tsconfig`.json, and I'm having issues with importing modules.

Still, several people reported having [a similar issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2238), and apparently [a fix is on the way](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2206). For now the suggestion is to revert back to `msal@1.3.2` and `@azure/msal-angular@1.0.0`. Apologies for that -can you confirm this helps with your case?

**Comment by patolax** [comment]
awsome, that worked. thanks.
