### ISSUE TITLE
Load config file dynamically from the server

### ISSUE THREAD

**Issue by patolax** [Azure-Samples/active-directory-b2c-javascript-angular-spa#19]
How to load the config from the server without hard coding in the .ts file.

I tried implementing the config loader and loading  MSAL_CONFIG and MSAL_CONFIG_ANGULAR from the server. But this approach ends up causing RENEW_TOKEN calls for each and every api call and module load. Is there a proper way to implement this?

```
 {
      provide: IDENTITY_CONFIG,
      useClass: ConfigLoaderService, // loader
    },
    {
      provide: APP_INITIALIZER,
      useFactory: IdentityConfigFactory,
      deps: [IDENTITY_CONFIG],
      multi: true,
    },
    {
      provide: MSAL_CONFIG,
      useFactory: msalConfigFactory,
      deps: [IDENTITY_CONFIG],
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: msalAngularConfigFactory,
      deps: [IDENTITY_CONFIG],
    },

```

Logs for a simple API call
[DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:19 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info RenewIdToken has been called
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:20 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info ProcessCallBack has been called. Processing callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:20 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info State status: true; Request type: LOGIN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:20 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:20 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info Fragment has idToken
:7100/#state=eyJpZCI6ImZhMGY0Mjc0LTRiZmYtNDQwMy04
Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:7100/Roboto-Regular.woff2
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:21 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info ProcessCallBack has been called. Processing callback from redirect response
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:21 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info State status: true; Request type: RENEW_TOKEN
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:21 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info State is right
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:21 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info Fragment has access token
development-logger.ts:10 [DEBUG] [MsalAuthService]:  MSAL Logging:  Tue, 01 Sep 2020 00:29:21 GMT:1c3a20ec-fb50-4269-94df-14a8fe56e84c-1.4.0-Info The user object received in the response is the same as the one passed in the acquireToken request

**Comment by derisen** [comment]
@patolax sorry for the delay. We plan to demonstrate this in the next upcoming sign-in sample. For the moment, did you had a chance to review the [initialization documentation here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md)?

**Comment by patolax** [comment]
Thanks I will have a look.
