### ISSUE TITLE
Sample should implement ngOnDestroy()

### ISSUE THREAD

**Issue by WorldMaker** [Azure-Samples/active-directory-b2c-javascript-angular-spa#21]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`

## Description

The `msal-angular` README points out that when subscribing to `broadcastService` events that the user should be careful to always unsubscribe (likely in a corresponding `ngOnDestroy()` lifecycle event). While the subscriptions in this sample are all made in the top most `app.component.ts` and unlikely for `ngOnDestroy()` to be called in an application lifetime, it still seems like it would be a good idea to implement the unsubscribes if for no other reason than "hygiene"/reflecting best practices especially when the best practice is already particularly pointed out in the library's README.

**Comment by derisen** [comment]
@WorldMaker This is a good point. I will make sure to add this in the next update (you are more than welcome if you would like to make a PR and add me as a reviewer)
