### ISSUE TITLE
Warning during compile: CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by hhubik** [Azure-Samples/active-directory-b2c-javascript-angular-spa#27]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `@azure/msal-angular@0.x.x`
- [x ] `@azure/msal-angular@1.4.2`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 9.1
## Description
Just cloned the sample repo on my system and followed the README instructions to install and start the app.
## Error Message
The following warning appears  in the compile window:

```
WARNING in D:\...\active-directory-b2c-javascript-angular-spa\node_modules\@azure\msal-angular\__ivy_ngcc__\fesm2015\azure-msal-angular.js depends on 'minimatch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
** Angular Live Development Server is listening on localhost:6420, open your browser on http://localhost:6420/ **
: Compiled successfully.
```
## Security

- [ ] Is this issue security related?

## Regression

- [ ] Did this behavior work before?

**Comment by jasonnutter** [comment]
@hhubik We're aware of this warning, and will be looking to address it in MSAL Angular v2, which we are working on currently. Is this causing any issues?

**Comment by hhubik** [comment]
@jasonnutter It's not a showstopper for me at the moment.  When will MSAL Angular v2 be out, very roughly?

**Comment by derisen** [comment]
@hhubik you can find the [project roadmap here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md).
