### ISSUE TITLE
Question: how to get user profile image

### ISSUE THREAD

**Issue by aosyatnik** [Azure-Samples/active-directory-b2c-javascript-angular-spa#29]
## Library

- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`

## Description

I tried `active-directory-b2c-javascript-angular-spa` and `active-directory-b2c-javascript-nodejs-webapi`, which are great examples. I'm wondering is there any way to get a user profile image(thumbnail). Something like it was for "normal" AAD https://graph.microsoft.com/v1.0/me/photo/$value, where you provide scope `user.read`. Is it possible to add anything like this in this example?

**Comment by derisen** [comment]
@aosyatnik thank you very much : ) Unfortunately, users cannot obtain an access token for MS Graph in a B2C application like this (unlike "normal" AAD). Please take a look at this document for more details: [Working with MSAL.js and Azure AD B2C](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md).

You can call MS Graph in a B2C app using app permissions. This mostly corresponds to [user management scenarios](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-operations). There is a .NET Core sample application illustrating this [here](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management). We are working on a similar application for the JavaScript ecosystem, but I don't have an ETA at the moment.

**Comment by derisen** [comment]
Closing, let us know if you need further help.
