### ISSUE TITLE
Bug: App continuously reloading the page while trying to make a request to a protected API

### ISSUE THREAD

**Issue by karrocon** [Azure-Samples/active-directory-b2c-javascript-angular-spa#32]
## Library

- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.0.0-alpha.4`

## Framework
@angular v11.0.0

## Description
When trying to make a request to a protected API client app keeps looping without actually making the request. 

## Error Message
No error message (see attached screenshot).
![image](https://user-images.githubusercontent.com/7526777/107390662-32b3a600-6af8-11eb-9417-76504416c512.png)

First token response (grant_type: authorization_code):
client_id: e28c4d7c-0b43-4670-b709-f5657ec3d4af
redirect_uri: https://localhost:44342/
scope: offline_access https://frontsystemsincubation.onmicrosoft.com/api/authentication/permissions.read openid profile
code: (code)
code_verifier: XdfptaQD_cR5nJAfMQj2ztbkc2d4nAMwViAPVtuEta0
grant_type: authorization_code
client_info: 1
client-request-id: 1808479b-d7f4-4b48-89ef-890f423dc95c

Second token response (grant_type: refresh_token):
client_id: e28c4d7c-0b43-4670-b709-f5657ec3d4af
scope: offline_access https://frontsystemsincubation.onmicrosoft.com/api/authentication/permissions.read openid profile
grant_type: refresh_token
client_info: 1
client-request-id: 7dad68ab-9a6e-4bd3-8b9d-11216e84ea95
refresh_token: (refresh_token)

## MSAL Configuration

app.module.ts
```js
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'e28c4d7c-0b43-4670-b709-f5657ec3d4af',
      authority: b2cPolicies.authorities.signIn.authority,
      redirectUri: 'https://localhost:44342/',
      postLogoutRedirectUri: 'https://localhost:44342/',
      navigateToLoginRequestUrl: true,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(apiConfig.uri, apiConfig.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [...apiConfig.scopes],
    },
  };
}
```

b2c-config.ts
```js
const baseAuthorityUrl = 'https://frontsystemsincubation.b2clogin.com/frontsystemsincubation.onmicrosoft.com';

/**
 * Enter here the user flows and custom policies for your B2C application,
 * To learn more about user flows, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
 * To learn more about custom policies, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview
 */
export const b2cPolicies = {
  names: {
    signIn: 'b2c_1_si',
    signUp: 'b2c_1_su',
    signUpSignIn: "b2c_1_susi",
    forgotPassword: "b2c_1_reset",
    editProfile: "b2c_1_profile"
  },
  authorities: {
    signIn: {
      authority: `${baseAuthorityUrl}/b2c_1_si`
    },
    signUp: {
      authority: `${baseAuthorityUrl}/b2c_1_su`
    },
    signUpSignIn: {
      authority: `${baseAuthorityUrl}/b2c_1_susi`,
    },
    forgotPassword: {
      authority: `${baseAuthorityUrl}/b2c_1_reset`,
    },
    editProfile: {
      authority: `${baseAuthorityUrl}/b2c_1_profile`
    }
  },
  authorityDomain: "frontsystemsincubation.b2clogin.com"
};

/**
 * Enter here the coordinates of your Web API and scopes for access token request
 * The current application coordinates were pre-registered in a B2C tenant.
 */
export const apiConfig: { scopes: string[]; uri: string } = {
  scopes: ['offline_access', 'https://frontsystemsincubation.onmicrosoft.com/api/authentication/permissions.read'],
  uri: 'http://localhost:5000'
};
```

## Reproduction steps

Using both samples with my own AAD B2C.

## Expected behavior

The client should be able to retrieve the token using the authorization code flow to make the request to the API with the required scope.

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
@karrocon this sample was meant to be used with [msal-angular-v1](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-angular-v1/lib/msal-angular). You might find [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample) more useful as it uses [msal-angular-v2](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) in an Angular 11 project. 

In any case, can you try setting `navigateToLoginRequestUrl` to **false**, as in:

```typescript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'e28c4d7c-0b43-4670-b709-f5657ec3d4af',
      authority: b2cPolicies.authorities.signIn.authority,
      redirectUri: 'https://localhost:44342/',
      postLogoutRedirectUri: 'https://localhost:44342/',
      navigateToLoginRequestUrl: false,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}
```

**Comment by karrocon** [comment]
Thank you for the quick response. Closing the issue here.
