### ISSUE TITLE
Do you have similar sample in React?

### ISSUE THREAD

**Issue by MNF** [Azure-Samples/active-directory-b2c-javascript-angular-spa#33]
If yes, please add the link to readme,
If no, it will be good to add some links how to do the same in other (non angular) technologies

**Comment by derisen** [comment]
@MNF there is a [similar sample here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample). Let me know if you need further help with it.

**Comment by derisen** [comment]
Closing. Let us know if you need further guidance.
