### ISSUE TITLE
acr claim is null

### ISSUE THREAD

**Issue by enniobolondi** [Azure-Samples/active-directory-b2c-javascript-angular-spa#7]
Hi,
just few thoughs.
First of all, please consider that ADB2C on Azure Portal has been successfully configured by me and is able to interact with my Angular application. Infact I'm happily able to sign-up a new user without problem.  
But, once I signin, it always returns the following message: 

> Password has been reset successfully. Please sign-in with your new password

I tryied to reset the password, but I always receive the same. I inspected the **Microsoft Code** and I discovered this line:

`      if (success.idToken.claims['acr'] !== b2cPolicies.names.signUpSignIn) {
        window.alert("Password has been reset successfully. \nPlease sign-in with your new password");
        return this.authService.logout()
      }`

I investigated a little bit further and I realized that the generated ADB2C JWTToken is missing the "acr" claim. And [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#claims), on Microsoft Official Documentation, they wrote:

> Used only with older policies.

So I'm wondering:

1. Is "acr" claim mandatory?
2. Can I comment out the line without affecting the stability? The application seems work and the returned JWT is well formed

Thanks and regards,
Ennio

**Comment by derisen** [comment]
1) `acr` claim is only required if you need to use password reset flow. For newer policies, its equivalent is `tfp` (let me know if you don't have that claim in your token).
2) you can certainly do that, if you don't need password reset flow.

And thank you for the feedback : ) I'll leave a remark in the source code for `acr` vs `tfp`.

**Comment by enniobolondi** [comment]
Thank you Derisen, you are right. The "tfp" token has the correct policy value (B2C_1_susi).
Really appreciate your support :-)

Thanks a lot
Ennio

**Comment by derisen** [comment]
cheers : ) closing this.
